name: Run Cypress Tests

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout o código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do projeto
        run: npm install

      - name: Rodar testes Cypress (modo headless)
        run: npm run test:ci

      - name: Upload de screenshots (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload de vídeos (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

